require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CatchesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Catch. As you add validations to Catch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CatchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all catches as @catches" do
      catch = Catch.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:catches)).to eq([catch])
    end
  end

  describe "GET show" do
    it "assigns the requested catch as @catch" do
      catch = Catch.create! valid_attributes
      get :show, {:id => catch.to_param}, valid_session
      expect(assigns(:catch)).to eq(catch)
    end
  end

  describe "GET new" do
    it "assigns a new catch as @catch" do
      get :new, {}, valid_session
      expect(assigns(:catch)).to be_a_new(Catch)
    end
  end

  describe "GET edit" do
    it "assigns the requested catch as @catch" do
      catch = Catch.create! valid_attributes
      get :edit, {:id => catch.to_param}, valid_session
      expect(assigns(:catch)).to eq(catch)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Catch" do
        expect {
          post :create, {:catch => valid_attributes}, valid_session
        }.to change(Catch, :count).by(1)
      end

      it "assigns a newly created catch as @catch" do
        post :create, {:catch => valid_attributes}, valid_session
        expect(assigns(:catch)).to be_a(Catch)
        expect(assigns(:catch)).to be_persisted
      end

      it "redirects to the created catch" do
        post :create, {:catch => valid_attributes}, valid_session
        expect(response).to redirect_to(Catch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved catch as @catch" do
        post :create, {:catch => invalid_attributes}, valid_session
        expect(assigns(:catch)).to be_a_new(Catch)
      end

      it "re-renders the 'new' template" do
        post :create, {:catch => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested catch" do
        catch = Catch.create! valid_attributes
        put :update, {:id => catch.to_param, :catch => new_attributes}, valid_session
        catch.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested catch as @catch" do
        catch = Catch.create! valid_attributes
        put :update, {:id => catch.to_param, :catch => valid_attributes}, valid_session
        expect(assigns(:catch)).to eq(catch)
      end

      it "redirects to the catch" do
        catch = Catch.create! valid_attributes
        put :update, {:id => catch.to_param, :catch => valid_attributes}, valid_session
        expect(response).to redirect_to(catch)
      end
    end

    describe "with invalid params" do
      it "assigns the catch as @catch" do
        catch = Catch.create! valid_attributes
        put :update, {:id => catch.to_param, :catch => invalid_attributes}, valid_session
        expect(assigns(:catch)).to eq(catch)
      end

      it "re-renders the 'edit' template" do
        catch = Catch.create! valid_attributes
        put :update, {:id => catch.to_param, :catch => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested catch" do
      catch = Catch.create! valid_attributes
      expect {
        delete :destroy, {:id => catch.to_param}, valid_session
      }.to change(Catch, :count).by(-1)
    end

    it "redirects to the catches list" do
      catch = Catch.create! valid_attributes
      delete :destroy, {:id => catch.to_param}, valid_session
      expect(response).to redirect_to(catches_url)
    end
  end

end
